ErikEJ/EFCorePowerTools

- README.md
The instructions for automatically getting the latest daily build are for SQLCeToolbox. Added correct Feed URL to use when following those instructions
> Added correct Feed URL

- src/GUI/ReverseEngineer20/ReverseEngineer/Pluralizer.cs
- src/GUI/UnitTests/PluralizerTest.cs
Fixes #60 
In the Pluralizer class, the suffix was being extracted using the last space in the string. I have included lines to extract suffix based on the last upper case letter in the string.
Also, I commented out  {"status", "status"} from _classicalInflectionList. Because of this, "status" suffix was considered as a plural word.
> Issue Fix #60

- src/GUI/EFCorePowerTools.Shared/Models/TableInformationModel.cs
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
- Tests for commands in PickTablesViewModel
- Bugfix for pre-selecting tables
- Simplified table filter for empty search text
- Made behavior between SaveSelection "Execute" and "CanExecute" persistent
- Remaining tests
> Tests for PickTablesViewModel

- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/Style.xaml
This improvements replace the Xceed control with the default Windows control, allowing more flexibility on the UI.
> UI improvements for PickTablesDialog

- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
Fix for #147 
Learning something new every day. The `IsThreeState` only defines the interactable behavior, but you can still set `null` from the code: https://stackoverflow.com/a/23364850/2132796
> CheckBox issue fix

- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
Adding a new connection via the 'Add...' wouldn't display anything in the ComboBox after adding a new conneciton. There would be an entry, but without any text. Those entries were however displayed correctly when opening the dialog again.
This fix resolves the issue, by keeping the display name throughout the layers.
> Bugfix for pick server / database dialog

- README.md
- Added VS marketplace badge
- change http links to https (where possible)
- remove "Visual Studio 2017", as it also works for 2019
live preview: https://github.com/304NotModified/EFCorePowerTools/blob/patch-1/README.md
> Updated README (badge, https, 2019)

- src/GUI/ReverseEngineer20/DacpacConsolidate/DacpacConsolidator.cs
parser.GetCustomData() throws FileNotFoundException for missing DACPACs.
The FileNotFoundException is OK if the reference of the root DACPAC is not found.
It is however not OK if the missing DACPAC is only referenced by another DACPAC than the root DACPAC, but not by the root DACPAC directly.
Therefore, skip missing DACPACs if they're not directly referenced by the root DACPAC.
> Fix for case 2 in #274

- src/GUI/EFCorePowerTools/Extensions/EnvDTEExtensions.cs
- src/GUI/ReverseEngineer20/DacpacConsolidate/DacpacConsolidator.cs
- src/GUI/ReverseEngineer20/DacpacConsolidate/DacpacMerger.cs
Follow-up to #274 and #369 
Stability Improvements:
- MAJOR: If a referenced DACPAC points to other DACPACs, and those DACPACs don't exist in the build output of our main project, it was included in the additional files. With this change, missing third-level DACPACs won't be included in the final reference list.
- MINOR: While building, the last write time might exceed two seconds, but the file was still built correctly. Validate against the build start time instead.
- MINOR: Accessing project.FullName might throw a NotImplementedException (from COM). In that case, the best match we can find is using the UniqueName.
Improved developer help:
- Added additional exception information for missing required references. This issues might be caused by an inconsistent usage of …
> Stability improvements and developer help

- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
`user_tables` does not have `owner` column; `all_tables` must be used:
Tested on 2 different DBs:
- **Oracle Database 11 EE**
- **Oracle Database 12 SE**
> Fix ORA-00904

- src/GUI/EFCorePowerTools/Contracts/ViewModels/IModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
`Loaded` command was triggered after `ApplyPresets`, therefore overwriting the saved presets.
> Fixed #400

- src/GUI/RevEng.Core/Procedures/Model/Metadata/ProcedureParameter.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
Addresses and issue where an exception is throw when executing a stored procedure that has been scaffolded containing a table valued parameter.
**Exception**
```
System.ArgumentException
HResult=0x80070057
Message=The table type parameter 'Shipments' must have a valid type name.
Source=Microsoft.Data.SqlClient
StackTrace:
at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at …
```
> Add Type Name for Table Valued Parameters 

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/RevEng.Core.50/RevEng.Core.50.csproj
- src/GUI/RevEng.Core.50/ServiceProviderBuilder.cs
- src/GUI/RevEng.Core/ServiceProviderBuilder.cs
- src/GUI/RevEng.Core/VisitorRelationScaffoldingModelFactory.cs
- src/GUI/RevEng.Shared/TableInformationModel.cs
- src/GUI/efreveng/TestFiles/efreveng572.txt
The modifications are quite simple. I have added the ExcludedColumns in the TableInformationModel. 
The awkward part is in the ReverseEngineerHandler. I had to replace predefined tables with preselected ones when the names match. This is necessary because the UI serializes from predefined tables and that would overwrite any change made by the user to the efpt.config.json file. If you have a better idea I'm all ears :)
> Adds ability to exclude columns from mapping during reveng

- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/TableInformationViewModel.cs
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
- src/GUI/UnitTests/ViewModels/TableInformationViewModelTests.cs
- Changed from ListBox to TreeView for tables and column selection
- Columns of unselected tables are also unselected. When user selects a table all columns are selected. User can unselect columns. 
- Enabled UI virtualization in TreeView and tested it with 700 tables and 6000 columns. Rendering time: less than a second on my laptop. This avoids columns lazy loading in the TreeView.
- Fixes #596
> Add UI to select column of a table

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/AdvancedModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
> Add UI for option to avoid nullable bools

- src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
Context : 
Having several efpt.config.json on a project, forced to have only one renaming file. 
Also, can't share renaming setup between efpt.config.json cause renaming file is getting purged with only matching config.
-- efpt.renaming.json
-- Base1
---- efpt.config.json
-- Base 2
---- efpt.config.json
Solution :
Look for renaming file on same folder than the config file. 
-- Base1
---- efpt.config.json
---- efpt.renaming.json
-- Base 2
---- efpt.config.json
---- efpt.renaming.json
> Search for renaming file in same folder as config file

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.it.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.tr.resx
- src/GUI/RevEng.Core.50/RevEng.Core.50.csproj
- src/GUI/RevEng.Core.60/RevEng.Core.60.csproj
- src/GUI/RevEng.Core.Abstractions/ModuleScaffolderOptions.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
- src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs
- src/GUI/RevEng.Core/ServiceProviderBuilder.cs
- src/GUI/RevEng.Core/Tables/CSharpModelGeneratorExtend.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/Shared/ViewModels/AdvancedModelingOptionsViewModel.cs
- src/GUI/Shared/ViewModels/ModelingOptionsViewModel.cs
I have introduced schema folder separation per issue: [https://github.com/ErikEJ/EFCorePowerTools/issues/158](https://github.com/ErikEJ/EFCorePowerTools/issues/158)
These changes include AdvancedModelingOptionsDialog and **Use schema folder separation** is added as the last option of Advance settings. You can see this in the following image. This setting is saved as UseSchemaFolders property in JSON and it is used through all changes in code.
There are a little bit complex changes inside **CleanUp** method because of supporting switching between schema and non-schema option and removing all directories and their files.
> Introduced schema folder separation and cleanup method improvements.

- src/GUI/RevEng.Core/Routines/SqlServerRoutineModelFactory.cs
We upgraded from EF_Core_Power_Tools_v2.5.**454** to EF_Core_Power_Tools_v2.5.**692** and stopped seeing the Stored Procedures listed on the "Choose Database Objects" form. After downgrading to 2.5.454 again we can reverse engineer procedures again.
The database collation is: SQL_Latin1_General_CP850_BIN
In SQL Profiler we can see lower case procedure being used for ROUTINE_TYPE and this query returns no results:
```
SELECT
ROUTINE_SCHEMA,
ROUTINE_NAME,
ROUTINE_TYPE,
CAST(CASE WHEN (ROUTINE_TYPE = 'FUNCTION' AND DATA_TYPE != 'TABLE') THEN 1 ELSE 0 END AS bit) AS IS_SCALAR
FROM INFORMATION_SCHEMA.ROUTINES
WHERE NULLIF(ROUTINE_NAME, '') IS NOT NULL
AND ROUTINE_TYPE = 'procedure'
ORDER BY ROUTINE_NAME;
```
The corrected SQL returns the expected data:
```
SELECT
ROUTINE_SCHEMA,
ROUTINE_NAME, …
```
> Use uppercase routineType to support databases with BIN collations

- src/GUI/RevEng.Core/README.md
I leaves `[ProviderName]`, `[ContextName]` and `[ConnectionString]` as a placeholder for replacement by the tool.
#1334
> A template for providing hints for initial setup after Reverse Engineer generated classes

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/PowerToolsExtensionPack/source.extension.vsixmanifest
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/efreveng60/BuildCmdlineTool.cmd
- src/GUI/efreveng70/BuildCmdlineTool.cmd
I modified the build files to also generate the reverse engineering console apps for arm64. When the extension loads on of them it determines what the cpu architecture it is on and extracts the correct one.
This is not the most elegant solution by any means but it leaves all of the original x64 build instructions and steps as untouched as possible
> Add Arm64 support for Reverse Engineering

- src/GUI/RevEng.Core.60/ReverseEngineerScaffolder.cs
Fix for duplicate semicolons in dbcontext file when using database schema namespaces and EF7 that uses C#10 using styles.
Fixes #1848 
- [X ] Bug fix (non-breaking change which fixes an issue)
Generating the files using Adventure Worker database with the `efreveng60` and `efreveng70` project versions.
> Fixes ErikEJ#1848. Duplicate semicolons in dbcontext file

- .github/workflows/cli-tool.yml
- src/GUI/efcpt.7/Services/PackageService.cs
- src/GUI/efcpt.7/readme.md
> Publish daily to Nuget

- samples/efcpt-config.json
- samples/efcpt-schema.json
- src/Core/NUnitTestCore/CliObjectListTest.cs
- src/Core/efcpt.7/HostedServices/ScaffoldHostedService.cs
- src/Core/efcpt.7/readme.md
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Cli/Configuration/CodeGeneration.cs
Adds new option to not refresh the object lists in the efcpt-config.json during subsequent scaffolds.  Useful when only scaffolding a small number of tables from a database that has many tables in it that are being excluded.  Closes #2100.
> Issue #2100  - Adds new option to not refresh the object lists in the efcpt-config.json during subsequent scaffolds

- samples/efcpt-schema.json
- src/Core/NUnitTestCore/CliObjectListTest.cs
- src/Core/efcpt.7/HostedServices/ScaffoldHostedService.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Function.cs
- src/GUI/RevEng.Shared/Cli/Configuration/IEntity.cs
- src/GUI/RevEng.Shared/Cli/Configuration/StoredProcedure.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Table.cs
- src/GUI/RevEng.Shared/Cli/Configuration/View.cs
* Closes #2106 and adds the functionality for it. 
* Reverts part of #2104 in order to support the ability to have excluded columns in the CLI.  The reverted portion is the skipping of fetching the schema definition when the `refresh-object-list` is `false`
> Add ability to exclude columns in the CLI config (feature exists in VS Plugin, adding for parity)

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.fr.vsct
- src/GUI/EFCorePowerTools/Locales/CompareLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.fr.resx
- src/GUI/EFCorePowerTools/VSPackage.fr.resx
> French localizations

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.ru.vsct
- src/GUI/EFCorePowerTools/Locales/AboutLocale.ru.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.ru.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.ru.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.ru.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.ru.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ru.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.ru.resx
- src/GUI/EFCorePowerTools/VSPackage.ru.resx
Localization files have been translated into Russian. #2034
> Russian localization

- src/Core/RevEng.Core.60/Procedures/SqlServerStoredProcedureScaffolder.cs
The earlier behavior generated the procedure call as `EXEC @returnValue = [dbo].[MyProc] @Param1, @Param2`
This PR changes the call to use named parameters, so we're not dependent on the order of parameters in the procedure call: `EXEC @returnValue = [dbo].[MyProc] @Param1=@Param1, @Param2=@Param2`
Fixes: #2258 
Tested via the CLI, which generates valid code for both normal and output variables:
`EXEC @returnValue = [dbo].[USP_ProcedureName] @SomeParam = @SomeParam, @OutputParam = @OutputParam OUTPUT...`
> Use named parameters in MSSQL stored procedure scaffolding

- src/Core/RevEng.Core.60/Procedures/SqlServerStoredProcedureScaffolder.cs
Since the procedure parameters are always nullable, set the `#nullable disable` annotation to the relevant files to reduce conflicts with projects using nullable reference types
Tested with the CLI - generates the expected annotations to the top of the two files - the interface definition and the implementation:
```
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
...
```
fixes #2261
> fix: #2261 set nullable annotation for procedure files

- src/Core/NUnitTestCore/Dacpac/DacpacTest.cs
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac.csproj
- src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs
In ef8 there is DefaultValue property in addition to DefaultValueSql. EF scaffolder looks at this property and if it's not-empty for 
a bool type, the result field will be generated as non-nullable bool. Since it's not filling now, it is always generated as bool?, which is different from what is generated directly from the database.
I've taken TryParseClrDefault implementation from efcore repository
https://github.com/dotnet/efcore/blob/017fb22e4b63003dc650905ea066b992895dc54d/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L843
https://github.com/dotnet/efcore/blob/017fb22e4b63003dc650905ea066b992895dc54d/src/Shared/SharedTypeExtensions.cs#L77
> fill DefaultValue for dacpac

- src/Core/RevEng.Core.60/PatchedSqlServerDatabaseModelFactory.cs
- src/Core/RevEng.Core.80/RevEng.Core.80.csproj
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
see https://github.com/dotnet/efcore/pull/34689
@MarkMpn FYI!
> Support DataVerse keys

- samples/efcpt-schema.json
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.80/PatchedSqlServerDatabaseModelFactory.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Function.cs
- src/GUI/RevEng.Shared/Cli/Configuration/IEntity.cs
- src/GUI/RevEng.Shared/Cli/Configuration/StoredProcedure.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Table.cs
- src/GUI/RevEng.Shared/Cli/Configuration/View.cs
- src/GUI/RevEng.Shared/SerializationTableModel.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/ViewModels/ObjectTreeViewModel.cs
- src/GUI/UnitTests/ReverseEngineerHelperTest.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
Handles #2518.   This works around https://github.com/dotnet/efcore/issues/11298.
Example:
Before:
```json
{
"name": "[dbo].[Widget]",
"exclude": false
},
```
```csharp
public void Configure(EntityTypeBuilder<Widget> entity)
{
entity.ToTable("Widget", tb =>
{
tb.HasTrigger("Widget_Insert");
tb.HasTrigger("Widget_Update");
});
entity.HasIndex(e => new { e.CompanyId, e.IsDeleted, e.WidgetName }, "IX_Widget_CompanyIdIsDeletedWidgetName");
entity.HasIndex(e => e.CompanyId, "UX_Widget_CompanyId_TopLevelWidget")
.IsUnique()
.HasFilter("([ParentWidgetId]=(0) AND [IsDeleted]=(0))");
}
```
After:
```json
{
"name": "[dbo].[Folder]",
"exclude": false,
"excludedIndexes": [
"UX_Folder_CompanyId_TopLevelFolder"
]
},
```
```csharp
public void Configure(EntityTypeBuilder<Widget> entity)
{ …
```
> Implements #2518 to allow for excluding specific indexes during scaffolding

- src/Core/RevEng.Core.60/ReverseEngineerRunner.cs
- src/Core/efcpt.8/Constants.cs
- src/Core/efcpt.8/HostedServices/ScaffoldHostedService.cs
- src/Core/efcpt.8/Options/ScaffoldOptions.cs
- src/Core/efcpt.8/Program.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Constants.cs
- src/GUI/Shared/Extensions/ProjectExtensions.cs
> Support custom renaming file name

- src/Core/RevEng.Core.60/ReverseEngineerScaffolder.cs
EF Core Power Tools CLI 8.1.463 for EF Core 8
when configuration ` use-schema-namespaces-preview: true`
It throws under Linux but works in Windows
```
error: System.InvalidOperationException: Sequence contains no matching element
at System.Linq.ThrowHelper.ThrowNoMatchException()
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaNamespaceToModel(String entityTypeSchema, String code, IEnumerable`1 schemas) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 400
at RevEng.Core.ReverseEngineerScaffolder.AppendSchemaFoldersAndNamespace(IModel databaseModel, ScaffoldedModel scaffoldedModel, Boolean useSchemaFolders, Boolean useSchemaNamespaces, IEnumerable`1 …
```
> fix: handle separator under linux

- src/Core/RevEng.Core.60/ReverseEngineerRunner.cs
- src/Directory.Build.Props
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.de.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.pl.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.pt-br.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.tr.resx
- src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs
fixes #2614 
@jwyza-pi FYI! Gave UseT4Split higher priority
> Obsolete preview DbContext splitting

- src/Core/RevEng.Core.60/ReverseEngineerScaffolder.cs
Do not make DbContext name start with an upper case letter
fixes #2644
> Do not make DbContext name start with an upper case letter

- src/GUI/Shared/Contracts/ViewModels/ITableInformationViewModel.cs
- src/GUI/Shared/ViewModels/ObjectTreeViewModel.cs
- src/GUI/Shared/ViewModels/PickTablesViewModel.cs
- src/GUI/Shared/ViewModels/TableInformationViewModel.cs
- test/ScaffoldingTester/ScaffoldingTester/efpt.config.json
Make ExcludeIndexes work with VS extension
fixes #2640
> Make ExcludeIndexes work with VS extension

- src/Core/RevEng.Core.80/ConnectionStringResolver.cs
- src/Core/RevEng.Core.80/DataverseModelFactoryExtension.cs
- src/Core/RevEng.Core.80/PatchedSqlServerDatabaseModelFactory.cs
- src/Core/RevEng.Core.80/RevEng.Core.80.csproj
- src/Core/RevEng.Core.80/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
- src/Core/efcpt.8/Options/ScaffoldOptions.cs
- src/GUI/EFCorePowerTools/Dialogs/ConnectionDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/ConnectionDialog.xaml.cs
- src/GUI/RevEng.Shared/DatabaseType.cs
- src/GUI/RevEng.Shared/Providers.cs
- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
> Add Snowflake support

- src/Core/RevEng.Core.80/RevEng.Core.80.csproj
- src/Core/RevEng.Core.80/Routines/ScaffoldHelper.cs
- src/Core/RevEng.Core.80/Routines/Scaffolder.cs
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
> Compensate for bad names from stored proc results

- src/Core/RevEng.Core.80/Routines/Procedures/PostgresStoredProcedureScaffolder.cs
- src/Core/RevEng.Core.80/Routines/Procedures/SqlServerStoredProcedureScaffolder.cs
> Do not capitalize

- src/Core/RevEng.Core.80/ConnectionStringResolver.cs
- src/Core/RevEng.Core.80/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
- src/Core/efcpt.9/efcpt.9.csproj
Add missing T4 split support for EF Core 9 CLI
fixes #2538
> EF Core 9 Firebird support

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/RevEng.Shared/Providers.cs
- src/GUI/Shared/Extensions/ProjectExtensions.cs
- src/GUI/Shared/Handlers/CliHandler.cs
- src/GUI/Shared/Helpers/SqlProjHelper.cs
- src/GUI/Shared/Shared.projitems
Treat .dacpac as more equal to .sqlproj
fixes #2736
> Support edit and refresh with CLI config file

- src/Core/RevEng.Core.80/Routines/Scaffolder.cs
This pull request adds functionality to handle the `money` store type when generating data annotations for entity properties. The change ensures that `money`-typed columns in the database are correctly represented in the code with `[Column(TypeName = "money")]`.
- Updated logic to check for the `money` store type when `useDecimalDataAnnotation` is enabled.
- Added an additional `else if` block to append the appropriate `[Column]` attribute for properties with `money` type.
```csharp
if (property.StoreType == "decimal" && useDecimalDataAnnotation)
{
Sb.AppendLine($"[Column(\"{property.Name}\", TypeName = \"{property.StoreType}({property.Precision},{property.Scale})\")]");
}
else if (property.StoreType == "money" && useDecimalDataAnnotation)
{
Sb.AppendLine($"[Column(\"{property.Name}\", …
```
> Add Support for `money` Store Type in Data Annotations 

- src/Core/NUnitTestCore/ClassicHumanizerPluralizerTest.cs
- src/Core/NUnitTestCore/CliConfigMapperTest.cs
- src/Core/NUnitTestCore/CliObjectListTest.cs
- src/Core/NUnitTestCore/ConnectionStringResolverTest.cs
- src/Core/NUnitTestCore/CustomHumanizerPluralizerTest.cs
- src/Core/NUnitTestCore/Dacpac/DacpacConsolidatorTest.cs
- src/Core/NUnitTestCore/Dacpac/DacpacTest.cs
- src/Core/NUnitTestCore/DbContextSplitterTest.cs
- src/Core/NUnitTestCore/Dgml/DgmlTest.cs
- src/Core/NUnitTestCore/NUnitTestCore.csproj
- src/Core/NUnitTestCore/ReplacingCandidateNamingServiceTests.cs
- src/Core/NUnitTestCore/SqlServerTypeExtensionsTest.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- tools/code-sign.txt
> Fix missing mapping and add test

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.vsct
- src/GUI/EFCorePowerTools/Wizard/Wiz1_PickServerDatabaseDialog.cs
- src/GUI/EFCorePowerTools/Wizard/Wiz2_PickTablesDialog.cs
- src/GUI/EFCorePowerTools/Wizard/Wiz3_EfCoreModelDialog.cs
- src/GUI/Shared/Handlers/ReverseEngineer/RevEngWizardHandler.cs
- src/GUI/Shared/ViewModels/WizardDataViewModel.cs
I tested these updates with multiple configuration files and multiple connections.  I verified that changing connections work as expected.   Note that once a configuration is selected that it can be viewed on the first page tab, but cannot be changed [perhaps future update?]; the wizard has to be exited and different configuration selected.
> Multiple configurations and connection changes fix

- src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/Scaffolding/SqlServerDacpacStoredProcedureModelFactory.cs
> Fixes multiple issue in stored proc mapping from a .dacpac

- .github/ISSUE_TEMPLATE/02_ask_a_question.yml
GitHub does not allow for options to be boolean values, instead they should be strings.
Fixing this so I can issue a question following the expected templating.
> fix: ask_a_question template options values

- global.json
- src/GUI/EFCorePowerTools/Wizard/Resources/Converter.xaml
- src/GUI/EFCorePowerTools/Wizard/Wiz1_PickServerDatabaseDialog.cs
- src/GUI/EFCorePowerTools/Wizard/Wiz1_PickServerDatabaseDialog.xaml
- src/GUI/Shared/Converter/BoolNullConverter.cs
- src/GUI/Shared/Shared.projitems
Added new BoolNullConverter so that it can control the Next Button IsEnabled value (only enabled if SelectedConnectionString is not null).  On the Config tab I made it more apparent that only the configuration path is displayed - removed combo and replaced with textbox.
> #2931 Next disabled until connect select

- src/GUI/EFCorePowerTools/Wizard/Wiz4_StatusDialog.xaml.cs
- src/GUI/Shared/Handlers/ReverseEngineer/RevEngWizardHandler.cs
fixes #3105 
Mark down editor extension attempts to open UI thread while wizard is still mid-await on UI thread (reentrancy deadlock).   Evolution of code allowed me to utilize the more simplified approach [used by legacy editor] for handling the readme markdown file.
Was able to duplicate and resolve issue.
> #3105 Resolved issue where EFPT hangs if Markdown extension is installed
