- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml.cs
- src/GUI/UnitTests/CheckListBoxTest.cs
- src/GUI/UnitTests/UnitTests.csproj
Addresses Issue #11. 
The search shows only the matching tables. This doesn't alter any selection. 
Just a simple search.
> Add a search textbox to the PickTablesDialog to search table

- src/GUI/ReverseEngineer20/ReverseEngineer/Pluralizer.cs
- src/GUI/UnitTests/PluralizerTest.cs
> Fix Issue #67

- src/GUI/ReverseEngineer20/ReverseEngineer/Pluralizer.cs
- src/GUI/UnitTests/PluralizerTest.cs
This adds bunch of unit tests for Pluralizer class, and some small updates in the Pluralizer class. Not big update, but I would appreciate if this gets reviewed and merged (if possible).
Thanks.
> Pluralizer Class Unit Tests

- src/GUI/ReverseEngineer20/ReverseEngineer/ReplacingCandidateNamingService.cs
- src/GUI/UnitTests/Services/ReplacingCandidateNamingServiceTests.cs
Please consider this PR as bug fixing.
> replacing name fix.

- src/GUI/EFCorePowerTools.BLL/ExtensionVersionService.cs
- src/GUI/EFCorePowerTools.BLL/InstalledComponentsService.cs
- src/GUI/UnitTests/BLL/ExtensionVersionServiceTests.cs
- src/GUI/UnitTests/BLL/InstalledComponentsServiceTests.cs
- src/GUI/UnitTests/Models/AboutExtensionModelTests.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/app.config
- src/GUI/UnitTests/packages.config
Added unit tests for 3 classes:
- AboutExtensionModel
- ExtensionVersionService
- InstalledComponentsService
> Added new unit tests

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/packages.config
> Downgraded Microsoft.Extensions.DependencyInjection to 2.1.0

- src/GUI/EFCorePowerTools/ViewModels/AboutViewModel.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/ViewModels/AboutViewModelTests.cs
- src/GUI/UnitTests/packages.config
Added unit tests for the `AboutViewModel` used in the about dialog.
For #116
> Added unit tests for AboutViewModel

- src/GUI/ReverseEngineer20/ReverseEngineer/ReplacingCandidateNamingService.cs
- src/GUI/UnitTests/Services/ReplacingCandidateNamingServiceTests.cs
This is the proposal to solve problem with wrong Inverse Property names.
> invert property naming for fk.

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
For the bug reported in #116 
Should add a little bit more safety.
> Added additional null-checks, just in case

- src/GUI/EFCorePowerTools/Contracts/ViewModels/IPickTablesViewModel.cs
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml.cs
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
- Added more tests for the ViewModel
- Moved more logic from the Dialog background class into the ViewModel
> More tests for the PickTablesViewModel

- src/GUI/EFCorePowerTools/Contracts/ViewModels/IPickTablesViewModel.cs
- src/GUI/EFCorePowerTools/Contracts/Views/IPickTablesDialog.cs
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Handlers/ServerDgmlHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
For #116 - final tests of the `PickTablesViewModel`.
All tests for that dialog are complete with this PR.
> Removed IncludeTables logic from ViewModel, moved to business logic

- src/GUI/EFCorePowerTools.Shared/Models/TableInformationModel.cs
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Handlers/ServerDgmlHandler.cs
- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/EFCorePowerTools/app.config
- src/GUI/EFCorePowerTools/packages.config
- src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs
- src/GUI/ReverseEngineer20/ReverseEngineer/CustomTemplateFileService.cs
- src/GUI/ReverseEngineer20/ReverseEngineer/DacpacTableListBuilder.cs
- src/GUI/ReverseEngineer20/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/ReverseEngineer20/ReverseEngineer20.csproj
- src/GUI/ReverseEngineer20/packages.config
- src/GUI/UnitTests/DacpacTest.cs
- src/GUI/UnitTests/Models/TableInformationModelTest.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
- src/GUI/UnitTests/ViewModels/TableInformationViewModelTests.cs
- src/GUI/UnitTests/app.config
- src/GUI/UnitTests/packages.config
> Work in progress - reveng using 2.2

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
Force early loading of system windows interactivity
> Fixes #153

- src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs
> Remove duplicate partial method from generated DbContext class

- src/GUI/EFCorePowerTools.Shared/Enums/ModelingGenerationMode.cs
- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Contracts/ViewModels/IModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/Contracts/Views/IEfCoreModelDialog.cs
- src/GUI/EFCorePowerTools/Contracts/Views/IModelingOptionsDialog.cs
- src/GUI/EFCorePowerTools/Converter/BoolInvertConverter.cs
- src/GUI/EFCorePowerTools/Dialogs/Converter.xaml
- src/GUI/EFCorePowerTools/Dialogs/EfCoreMigrationsDialog.xaml.cs
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml.cs
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs
Changes for #116 
Before:
After:
@ErikEJ This would require some additional QS from your side. I think I got all the logic right as it was, but a second look might not hurt 😉 
Also I had a "how could this ever work" moment in `EfCoreReverseEngineer.GenerateFiles`.
> Refactored EfCoreModelDialog to MVVM

- README.md
- src/GUI/EFCorePowerTools/Dialogs/AboutDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/packages.config
Replaced Blend reference with NuGet package reference, as described in https://blogs.msdn.microsoft.com/dotnet/2018/12/10/open-sourcing-xaml-behaviors-for-wpf/
> Fixed issue with reference to Blend

- src/GUI/EFCorePowerTools/ViewModels/PickServerDatabaseViewModel.cs
- src/GUI/UnitTests/ViewModels/PickServerDatabaseViewModelTests.cs
> Pre-select database project if no database connection is available

- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
Adding a new mysql connection through reverse engineering was initially missed.
> Fix #193 not adding mysql connection through reverse engineer

- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
> Get Postgres views

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs
- src/GUI/efreveng/ReverseEngineer/ReverseEngineerRunner.cs
> Enable total control of namespaces and folder paths for EntityTypes and DbContext

- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/Handlers/ServerDgmlHandler.cs
- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
- src/GUI/EFCorePowerTools/Helpers/RepositoryHelper.cs
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/ErikEJ.EntityFrameworkCore.DgmlBuilder/ErikEJ.EntityFrameworkCore.DgmlBuilder.csproj
- src/GUI/RevEng.Shared/TableInformationModel.cs
- src/GUI/ReverseEngineer20/ReverseEngineer/DacpacTableListBuilder.cs
- src/GUI/ReverseEngineer20/ReverseEngineerOptions.cs
> Visualize keyless tables and views (for EF Core 3.0 only)

- src/GUI/EFCorePowerTools/Extensions/CustomNameOptionsExtensions.cs
- src/GUI/EFCorePowerTools/Extensions/ReverseEngineerOptionsExtensions.cs
- src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs
- src/GUI/ReverseEngineer20/ServiceProviderBuilder.cs
- src/GUI/efreveng/ReverseEngineer/ReverseEngineerRunner.cs
- src/GUI/efreveng/ReverseEngineer/ServiceProviderBuilder.cs
- src/GUI/efreveng/efreveng.csproj
fixes #299 
fixes #253 
improves #294
> Efcore3 bug fixes

- src/GUI/EFCorePowerTools/Dialogs/EfCoreMigrationsDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
> Support large environment font

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Helpers/ReverseEngineerHelper.cs
- src/GUI/ReverseEngineer20/ReverseEngineer/DacpacTableListBuilder.cs
- src/GUI/UnitTests/DacpacTest.cs
- src/GUI/UnitTests/ReverseEngineerTest.cs
- src/GUI/UnitTests/UnitTests.csproj
Return proper table names from dacpac
fixes #304
> Preserve pre-2.3 table selections

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
- src/GUI/EFCorePowerTools/Helpers/RepositoryHelper.cs
- src/GUI/EFCorePowerTools/Resources.Designer.cs
- src/GUI/EFCorePowerTools/Resources.resx
- src/GUI/EFCorePowerTools/packages.config
- src/GUI/RevEng.Shared/DatabaseType.cs
- src/GUI/ReverseEngineer20/ReverseEngineer20.csproj
- src/GUI/ReverseEngineer20/ServiceProviderBuilder.cs
- src/GUI/ReverseEngineer20/packages.config
> I have no clue what I am doing!

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs
- src/GUI/ReverseEngineer20/ReverseEngineer/DbContextSplitter.cs
- src/GUI/ReverseEngineer20/ReverseEngineer20.csproj
- src/GUI/ReverseEngineer20/ReverseEngineerOptions.cs
- src/GUI/efreveng/ReverseEngineer/ReverseEngineerRunner.cs
- src/GUI/efreveng/efreveng.csproj
> Enable DbContext splitting

- src/GUI/efreveng/ReverseEngineer/CommentCSharpEntityTypeGenerator.cs
- src/GUI/efreveng/ReverseEngineer/ServiceProviderBuilder.cs
- src/GUI/efreveng/efreveng.txt
> Add comments!

- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/Extensions/ZipArchiveExtensions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/TableListBuilder.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
> Enable EF Core 5 preview 6 reverse engineering

- src/GUI/EFCorePowerTools.Shared/DAL/IVisualStudioAccess.cs
- src/GUI/EFCorePowerTools/DAL/VisualStudioAccess.cs
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs
- src/GUI/EFCorePowerTools/ViewModels/PickServerDatabaseViewModel.cs
- src/GUI/UnitTests/ViewModels/PickServerDatabaseViewModelTests.cs
> Prompt for .dacpac

- src/GUI/RevEng.Core/Check.cs
- src/GUI/RevEng.Core/ServiceProviderBuilder.cs
- src/GUI/RevEng.Core/SqlServerFasterDatabaseModelFactory.cs
Fixes https://github.com/dotnet/efcore/issues/22287
> Add faster SQL Server model factory (for 3.x)

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Contracts/ViewModels/IAdvancedModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/Contracts/Views/IAdvancedModelingOptionsDialog.cs
- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml.cs
- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/AdvancedModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/ViewModels/AdvancedModelingOptionsViewModelTests.cs
> New advanced dialog

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
> Add password prompt back that was lost during a refactor

- src/GUI/RevEng.Core/DbContextSplitter.cs
> Place EntityConfiguration files in seperate folder

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
> Prevent getting table list from blocking UI

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/RevEng.Core.50/RevEng.Core.50.csproj
- src/GUI/RevEng.Core.50/ServiceProviderBuilder.cs
- src/GUI/RevEng.Core/ColumnRemovingScaffoldingModelFactory.cs
- src/GUI/RevEng.Core/ServiceProviderBuilder.cs
- src/GUI/efreveng/TestFiles/efreveng572.txt
> Implement excluded columns

- src/GUI/RevEng.Core/Procedures/SqlServerSqlTypeExtensions.cs
> Support sql_variant with stored procedure mappings

- src/GUI/EFCorePowerTools/Contracts/ViewModels/IPickTablesViewModel.cs
- src/GUI/EFCorePowerTools/Contracts/Views/IPickTablesDialog.cs
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Helpers/ReverseEngineerHelper.cs
- src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
- src/GUI/RevEng.Core/ColumnRemovingScaffoldingModelFactory.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/RevEng.Shared/SerializationTableModel.cs
- src/GUI/RevEng.Shared/TableModel.cs
- src/GUI/UnitTests/ReverseEngineerHelperTest.cs
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
Bug fix: Bring back table list images
Bug fix: Rename Columns => ExcludedColumns
> Split TableColum and SerializationTableColumn classes

- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml.cs
Add uncheck warning
fixes #583
> Small tooltip changes

- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs
> Scaffold correct schema for table types

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/DacPacEngine/DacpacTableListBuilder.cs
- src/GUI/NUnitTestCore/ReplacingCandidateNamingServiceTests.cs
- src/GUI/RevEng.Core/ReplacingCandidateNamingService.cs
- src/GUI/RevEng.Core/TableListBuilder.cs
- src/GUI/RevEng.Shared/TableModel.cs
- src/GUI/UnitTests/Models/TableIModelTest.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
- src/GUI/UnitTests/ViewModels/PickTablesViewModelTests.cs
- src/GUI/efreveng/Program.cs
Remove HasPrimaryKey
Fix Replacing bug
> Add actual schema and name to TableModel

- src/GUI/EFCorePowerTools/Extensions/CustomNameOptionsExtensions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
> Support alternate renaming path, allowing multiple renaming files per project

- src/GUI/EFCorePowerTools/Extensions/CustomNameOptionsExtensions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
> Return potentially changed renaming path

- src/GUI/RevEng.Core/DbContextExtensions
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
> Provide cancellation token to SP mappers

- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
> Reverse Engineering - Always return TEntity[] from SP mapper

- src/GUI/RevEng.Core/DbContextExtensions
No mapping to a relational type can be found for the CLR type 'SqlParameter[]
> Fixed runtime exception

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
> Preserve renaming schemas without any tables

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/RevEng.Core/ReplacingCandidateNamingService.cs
- src/GUI/RevEng.Shared/ColumnNamer.cs
- src/GUI/RevEng.Shared/Schema.cs
- src/GUI/RevEng.Shared/SerializationTableModel.cs
- src/GUI/RevEng.Shared/TableRenamer.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
Improve (minimize) config serialization
Fix NRE bug
fixes #645
> Fix renamer serialization

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/Helpers/Telemetry.cs
- src/GUI/EFCorePowerTools/ViewModels/AboutViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/SchemaInformationViewModel.cs
- src/GUI/EFCorePowerTools/packages.config
> adding telemetry back

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
> Allow schemaName to be null

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
> Preserve equal column renamers

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
> Fix duplicated ignored renamers

- src/GUI/EFCorePowerTools/ViewModels/ObjectTreeViewModel.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- test/ScaffoldingTester/ScaffoldingTester/Models/NorthwindContextProcedures.cs
- test/ScaffoldingTester/ScaffoldingTester/Program.cs
Fix renaming serialization bug
fixes #684
> Append "Async" to stored procedure names

- src/GUI/RevEng.Core/DbContextSplitter.cs
- test/ScaffoldingTester/ConsoleApp/Models/ChinookContext.cs
- test/ScaffoldingTester/ConsoleApp/Models/ChinookContextProcedures.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/AlbumConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/ArtistConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/CustomerConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/EmployeeConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/GenreConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/InvoiceConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/InvoiceLineConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/MediaTypeConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/PlaylistConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/PlaylistTrackConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/TitleConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/Models/Configurations/TrackConfiguration.cs
- test/ScaffoldingTester/ConsoleApp/efpt.config.json
> Add partial method to split configuration classes and make them partial

- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
I was using a custom version but today I updated to latest version and found this bug...
> Fix schema(s) list not read from config if present

- src/GUI/EFCorePowerTools/Contracts/Views/IPickServerDatabaseDialog.cs
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/RevEng.Shared/CodeGenerationMode.cs
> preserve selected code generation mode

- src/GUI/EFCorePowerTools/Contracts/ViewModels/IPickServerDatabaseViewModel.cs
- src/GUI/EFCorePowerTools/Contracts/Views/IPickServerDatabaseDialog.cs
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/PickServerDatabaseViewModel.cs
- test/ScaffoldingTester/ScaffoldingTester/efpt.config.json
> Pre select the database connection based on the  last one used, if possible

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs
- src/GUI/RevEng.Core.50/RevEng.Core.50.csproj
- src/GUI/RevEng.Core/ServiceProviderBuilder.cs
- src/GUI/RevEng.Core/TableListBuilder.cs
> Enable EF Core 5 Oracle provider

- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- test/ScaffoldingTester/ScaffoldingTester/Models/NorthwindContextProcedures.cs
- test/ScaffoldingTester/ScaffoldingTester/Program.cs
> Add extension method for easy access to stored procedures from DbContext

- src/GUI/EFCorePowerTools/Extensions/EnvDTEExtensions.cs
resolve bug where project dont have projectitem
simplefy getfiles
> resolve bug where project dont have projectitem

- src/GUI/EFCorePowerTools/Handlers/Compare/CompareHandler.cs
- src/GUI/EFCorePowerTools/Handlers/ModelAnalyzerHandler.cs
- src/GUI/EFCorePowerTools/Handlers/ProcessLauncher.cs
- src/GUI/EFCorePowerTools/ViewModels/MigrationOptionsViewModel.cs
- src/GUI/efpt30.core/EFCoreMigrationsBuilder.cs
- src/GUI/efpt30.core/Program.cs
> fix dbContext list

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
> Use renamers during refresh

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/ViewModels/PickServerDatabaseViewModel.cs
Persist UIHint for .dacpac
fixes #803
> Fix .dacpac crash

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/EFCorePowerTools/ViewModels/AdvancedModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacStoredProcedureModelFactory.cs
- src/GUI/RevEng.Core/Functions/SqlServerFunctionModelFactory.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs
- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/efreveng/TestFiles/fulltest.json
> Add option to ignore objectfilter for efpt.config.json file

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/EFCorePowerTools/Properties/AssemblyInfo.cs
- src/GUI/NUnitTestCore/SqlServerTypeExtensionsTest.cs
- src/GUI/RevEng.Core/Procedures/SqlServerSqlTypeExtensions.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- test/ScaffoldingTester/ScaffoldingTester/Models/NorthwindContextProcedures.cs
- test/ScaffoldingTester/ScaffoldingTester/efpt.config.json
Fix missing support for sysname return value with stored procedures
> Avoid extract of efreveng tool every time

- src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/RevEng.Core/DbContextSplitter.cs
- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
> Disable all support for nullable types with .NET Framework

- src/GUI/EFCorePowerTools/Dialogs/AboutDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/CompareResultDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/Converter.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.zh.vsct
- src/GUI/EFCorePowerTools/Locales/AboutLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/AboutLocale.resx
- src/GUI/EFCorePowerTools/Locales/AboutLocale.zh.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/CompareLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.zh.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.zh.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.zh.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.zh.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.zh.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.zh.resx
- src/GUI/EFCorePowerTools/Resources.zh.resx
- src/GUI/EFCorePowerTools/VSPackage.zh.resx
- src/GUI/EFCorePowerTools/ViewModels/MigrationOptionsViewModel.cs
> Add Chinese translate

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.tr.vsct
- src/GUI/EFCorePowerTools/Locales/AboutLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.tr.resx
- src/GUI/EFCorePowerTools/Resources.tr.resx
- src/GUI/EFCorePowerTools/VSPackage.tr.resx
I don't know why but I don't see localize texts in right click dialog. Every other screen seems fine.
Thank you for great add-in. Appreciated.
> Add Turkish localization

- src/GUI/EFCorePowerTools/Helpers/VsDataHelper.cs
- src/GUI/RevEng.Core.50/RevEng.Core.50.csproj
- src/GUI/RevEng.Core/Functions/SqlServerFunctionModelFactory.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs
- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
- src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs
Refactor ReverseEngineerRunner to make it smaller
fixes #869
> Fall back to user type for parameters

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
- src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs
> Avoid unneeded files saved to disk

- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- test/ScaffoldingTester/ScaffoldingTester/Models/NorthwindContextProcedures.cs
> Enable mocking of stored procedure class

- src/GUI/EFCorePowerTools/Dialogs/ConnectionDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs
- src/GUI/EFCorePowerTools/ViewModels/PickConnectionViewModel.cs
- src/GUI/RevEng.Core.50/RevEng.Core.50.csproj
- src/GUI/RevEng.Core/RevEng.Core.csproj
- src/GUI/RevEng.Core/ServiceProviderBuilder.cs
- src/GUI/RevEng.Shared/DatabaseType.cs
relates to #884
relates to #288
> Initial support for Firebird

- src/GUI/EFCorePowerTools.Shared/Models/ModelingOptionsModel.cs
- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/Converter.xaml
- src/GUI/EFCorePowerTools/Dialogs/Style.xaml
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.it.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.zh-Hans.resx
- src/GUI/EFCorePowerTools/ViewModels/AdvancedModelingOptionsViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/ModelingOptionsViewModel.cs
- src/GUI/RevEng.Core.Abstractions/ModuleScaffolderOptions.cs
- src/GUI/RevEng.Core/DbContextExtensions
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
Proposal
Option for stored procedures return List instead of array
> Stored procedures return list

- src/GUI/EFCorePowerTools/DAL/ICredentialStore.cs
- src/GUI/EFCorePowerTools/Dialogs/ConnectionDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/Helpers/CredentialStore.cs
- src/GUI/EFCorePowerTools/ViewModels/PickConnectionViewModel.cs
- src/GUI/EFCorePowerTools/ViewModels/PickServerDatabaseViewModel.cs
- src/GUI/UnitTests/BLL/CredentialStoreTest.cs
- src/GUI/UnitTests/UnitTests.csproj
- src/GUI/UnitTests/ViewModels/PickServerDatabaseViewModelTests.cs
> Store ad-hoc credentials in Credential Manager

- src/GUI/DacFxStrongTypedCore/DacFxStrongTypedCore.csproj
- src/GUI/ErikEJ.EntityFrameworkCore.5.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.5.SqlServer.Dacpac.csproj
- src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.csproj
Update to latest DacFX
fixes #883
> Fix broken EF Core 5.0 Dacpac NuGet package

- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
> not add tag after enable HandleBars

- src/GUI/RevEng.Core.50/CommentCSharpEntityTypeGenerator.cs
- src/GUI/RevEng.Core/CommentCSharpEntityTypeGenerator.cs
#716 My proposed fix to that issue
> Fixed nullable navigation property

- src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs
> Use regex to rename functions and stored procedures

- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/ViewModels/PickTablesViewModel.cs
- src/GUI/efreveng/TestFiles/fulltestProceduresOnly.json
fixes #1041
fixes #1002
fixes #713
> Allow stored procedures only!

- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
> Work around table names with single quotes

- src/GUI/RevEng.Core/Routines/SqlServerRoutineModelFactory.cs
> Exclude system stored procedures and functions

- src/GUI/RevEng.Core/Routines/SqlServerRoutineModelFactory.cs
fixes #1056 (caused by wrong fix of #1050)
> Avoid filtering out non dbo schemas

- src/GUI/RevEng.Core/ReverseEngineerRunner.cs
> Fix too agressive clean up

- src/GUI/RevEng.Core/Procedures/SqlServerSqlTypeExtensions.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/GUI/RevEng.Core/Routines/SqlServerRoutineModelFactory.cs
- src/GUI/efreveng/TestFiles/fulltestMultiResult.json
> Support geo types as sproc parameters

- src/GUI/Shared/Helpers/NuGetHelper.cs
This PR fixes https://github.com/ErikEJ/EFCorePowerTools/issues/1332
> Fix a bug on InstallPackageAsync() method

- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
I have missed some places for MARS (https://github.com/ErikEJ/EFCorePowerTools/issues/1417). There is the fix.
> Fix MARS for UseAsyncCalls:false option (#1417)

- src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacStoredProcedureModelFactory.cs
- src/GUI/RevEng.Core.Abstractions/Metadata/Routine.cs
- src/GUI/RevEng.Core.Abstractions/ModuleModelFactoryOptions.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs
- src/GUI/RevEng.Core/Routines/SqlServerRoutineModelFactory.cs
- src/GUI/RevEng.Shared/SerializationTableModel.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/efreveng/TestFiles/fulltest.json
> Enable mapping of entity types to stored procedure result

- src/GUI/RevEng.Core.Abstractions/Metadata/ModuleParameter.cs
- src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureModelFactory.cs
- src/GUI/RevEng.Core/Routines/SqlServerRoutineModelFactory.cs
> Minimize database roundtrips with stored procedure/function scaffolding

- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/Shared/Contracts/ViewModels/IPickServerDatabaseViewModel.cs
- src/GUI/Shared/Contracts/Views/IPickServerDatabaseDialog.cs
- src/GUI/Shared/Extensions/ProjectExtensions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
- src/GUI/Shared/ViewModels/PickServerDatabaseViewModel.cs
> Offer EF Core choices based on project target framework

- src/GUI/NUnitTestCore/ReplacingCandidateNamingServiceTests.cs
- src/GUI/RevEng.Core/ReplacingCandidateNamingService.cs
> Fix up regex replaced column names

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/RevEng.Shared/ColumnNamer.cs
- src/GUI/Shared/Extensions/ProjectExtensions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/RenamingRulesSerializer.cs
- src/GUI/Shared/Helpers/RoslynEntityPropertyRenamer.cs
- src/GUI/Shared/Helpers/RoslynExtensions.cs
- src/GUI/Shared/Shared.projitems
- test/ScaffoldingTester/ScaffoldingTester5/efpt.refrenaming.json
> Enable renaming of navigation and reference properties

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/POCOEntityType.t4
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
- src/GUI/Shared/ViewModels/ModelingOptionsViewModel.cs
> Add POCO T4 option

- src/GUI/EFCorePowerTools/Resources.Designer.cs
- src/GUI/EFCorePowerTools/Resources.en.resx
- src/GUI/EFCorePowerTools/Resources.resx
- src/GUI/Shared/Helpers/VsDataHelper.cs
> Add support for Microsoft.Data.SqlClient DDEX provider added in VS 17.5

- src/GUI/EFCorePowerTools/Dialogs/EfCoreModelDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/RevEng.Core/TableListBuilder.cs
- src/GUI/RevEng.Shared/ColumnModel.cs
- src/GUI/RevEng.Shared/MapppingType.cs
- src/GUI/RevEng.Shared/ReverseEngineerResult.cs
- src/GUI/RevEng.Shared/SerializationTableModel.cs
- src/GUI/Shared/DAL/VisualStudioAccess.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
- src/GUI/Shared/Options/AdvancedOptions.cs
- src/GUI/UnitTests/ViewModels/ObjectTreeViewModelTests.cs
- test/Ef7Playground/Ef7Playground/Ef7Playground.csproj
- test/Ef7Playground/Ef7Playground/Models/NorthwindContext.cs
- test/Ef7Playground/Ef7Playground/Models/Special.cs
- test/Ef7Playground/Ef7Playground/efpt.config.json
> Smarter packages

- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.en.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.it.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.tr.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.zh-Hans.vsct
- src/GUI/Shared/Handlers/ReverseEngineer/ResultDeserializer.cs
- src/GUI/Shared/Handlers/ServerDgmlHandler.cs
- src/GUI/Shared/PkgCmdIDList.cs
- src/GUI/Shared/Shared.projitems
> Database viz

- src/GUI/DacFxStrongTypedCore/ModelMessages.Designer.cs
- src/GUI/DacFxStrongTypedCore/ModelMessages.es.resx
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.es.vsct
- src/GUI/EFCorePowerTools/Locales/AboutLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.es.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.es.resx
- src/GUI/EFCorePowerTools/VSPackage.es.resx
Added resources and .vsct file for Spanish language.
- [x ] New feature (non-breaking change which adds functionality)
With the Visual Studio debugger.
> Adding Spanish translation

- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/Shared/Extensions/ReverseEngineerOptionsExtensions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/efcpt/HostedServices/ScaffoldHostedService.cs
Fix CLI bug - output option was unused
fixes #1876
> Enable relative path for t4 template path

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.fr.vsct
- src/GUI/Shared/Handlers/ServerDgmlHandler.cs
fixes #2042
Also add missing fr vsct file
> Enable database dgml schema from a .dacpac

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.tr.vsct
- src/GUI/EFCorePowerTools/Locales/CompareLocale.tr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.tr.resx
I've added missing translations and some that were not translated before.
> Added missing turkish translations.

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs.vsct
- src/GUI/EFCorePowerTools/Locales/AboutLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.cs.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.cs.resx
- src/GUI/EFCorePowerTools/VSPackage.cs.resx
- added Czech localization
- UI needs some positioning changes because of longer texts (Rate, Help, Search, ...) :-)
> Czech localization

- src/GUI/EFCorePowerTools/Dialogs/AdvancedModelingOptionsDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.it.vsct
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.Designer.cs
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.it.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.resx
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Models/ModelingOptionsModel.cs
- src/GUI/Shared/ViewModels/AdvancedModelingOptionsViewModel.cs
- src/GUI/Shared/ViewModels/ModelingOptionsViewModel.cs
Also added some missing italian translations.
> Added T4 template path to Advanced dialog box. 

- src/GUI/EFCorePowerTools/Locales/CompareLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.en.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.fr.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.fr.resx
I reviewed and updated all of the french translations while also fixing a few minor typos in the english translations.
> Updated french translations.

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.jp.vsct
- src/GUI/EFCorePowerTools/Locales/AboutLocale.jp.resx
- src/GUI/EFCorePowerTools/Locales/CompareLocale.jp.resx
- src/GUI/EFCorePowerTools/Locales/DgmlLocale.jp.resx
- src/GUI/EFCorePowerTools/Locales/MigrationsLocale.jp.resx
- src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.jp.resx
- src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.jp.resx
- src/GUI/EFCorePowerTools/Locales/SharedLocale.jp.resx
- src/GUI/EFCorePowerTools/VSPackage.jp.resx
> Add Japanese localization

- src/Core/RevEng.Core.60/ReplacingCandidateNamingService.cs
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerOptions.cs
> Add support for prefix naming in EF Core 8

- samples/efcpt-schema.json
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Cli/Configuration/CodeGeneration.cs
> Add prefix naming support to CLI

- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Cli/Configuration/CliConfig.cs
- src/GUI/RevEng.Shared/Cli/Configuration/CodeGeneration.cs
- src/GUI/RevEng.Shared/Cli/Configuration/FileLayout.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Function.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Names.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Replacements.cs
- src/GUI/RevEng.Shared/Cli/Configuration/StoredProcedure.cs
- src/GUI/RevEng.Shared/Cli/Configuration/Table.cs
- src/GUI/RevEng.Shared/Cli/Configuration/TypeMappings.cs
- src/GUI/RevEng.Shared/Cli/Configuration/View.cs
> A cleaner, ordered config file for the CLI

- .github/workflows/cli-release.yml
- .github/workflows/cli-tool.yml
- .github/workflows/codeql.yml
- .github/workflows/nupkg-release.yml
- .github/workflows/vsix.yml
- global.json
so we can ensure a reliable and consistent sdk version
> add a global.json

- src/GUI/Shared/Extensions/ReverseEngineerUserOptionsExtensions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerUserOptions.cs
- src/GUI/Shared/Options/AdvancedOptions.cs
- src/GUI/Shared/Shared.projitems
> Save UiHint in another file

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.en.vsct
- src/GUI/Shared/GuidList.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/VsDataHelper.cs
- src/GUI/Shared/PkgCmdIDList.cs
> Server explorer context menu to launch

- .github/workflows/cli-tool.yml
- .github/workflows/vsix.yml
- src/Core/efreveng60/BuildCmdlineTool.cmd
- src/Core/efreveng70/BuildCmdlineTool.cmd
- src/Core/efreveng80/BuildCmdlineTool.cmd
- src/GUI/EFCorePowerTools/source.extension.vsixmanifest
- src/GUI/PowerToolsExtensionPack/source.extension.vsixmanifest
> Support VS on ARM64

- src/Directory.Build.Props
- src/GUI/EFCorePowerTools/Dialogs/ConnectionDialog.xaml
- src/GUI/EFCorePowerTools/Dialogs/ConnectionDialog.xaml.cs
- src/GUI/EFCorePowerTools/Dialogs/PickServerDatabaseDialog.xaml
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.de.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.en.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.es.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.fr.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.it.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.ja.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.pl.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.pt-br.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.ru.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.tr.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.zh-Hans.vsct
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.zh-Hant.vsct
- src/GUI/EFCorePowerTools/source.extension.vsixmanifest
fixes #2269 
Remove Azure SQL from ad-hoc dialog
Re-order menu items on Connection type dropdown
> Issue 2269 - add Server Explorere context menu for all languages

- src/Core/RevEng.Core.60/Dgml/DatabaseModelToDgml.cs
- src/Core/RevEng.Core.60/Dgml/DgmlHelper.cs
> Improve DB DGML sligthly

- src/Core/RevEng.Core.60/Functions/SqlServerFunctionScaffolder.cs
- src/Core/RevEng.Core.60/Procedures/PostgresProcedureServiceCollectionExtensions.cs
- src/Core/RevEng.Core.60/Procedures/PostgresStoredProcedureModelFactory.cs
- src/Core/RevEng.Core.60/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/Core/RevEng.Core.60/Routines/PostgresRoutineModelFactory.cs
- src/Core/RevEng.Core.60/Routines/RoutineScaffolder.cs
- src/Core/RevEng.Core.60/Routines/SqlServerRoutineModelFactory.cs
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.60/TableListBuilder.cs
> Postgres stored procedure discovery implemented

- src/Core/RevEng.Core.60/Functions/SqlServerFunctionScaffolder.cs
- src/Core/RevEng.Core.60/Procedures/PostgresNpgsqlTypeExtensions.cs
- src/Core/RevEng.Core.60/Procedures/PostgresStoredProcedureModelFactory.cs
- src/Core/RevEng.Core.60/Procedures/SqlServerSqlTypeExtensions.cs
- src/Core/RevEng.Core.60/Procedures/SqlServerStoredProcedureModelFactory.cs
- src/Core/RevEng.Core.60/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/Core/RevEng.Core.60/Routines/PostgresRoutineModelFactory.cs
- src/Core/RevEng.Core.60/Routines/ProcedureScaffolder.cs
Postgres: start work on type mapping
> Postgres: get result shape

- src/Core/RevEng.Core.60/Routines/Extensions/PostgresNpgsqlTypeExtensions.cs
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
> Postgres Initial type mapping

- src/Core/RevEng.Core.60/ReverseEngineerRunner.cs
- src/Core/RevEng.Core.60/Routines/Extensions/PostgresClrTypeMapper.cs
- src/Core/RevEng.Core.60/Routines/Extensions/PostgresNpgsqlTypeExtensions.cs
- src/Core/RevEng.Core.60/Routines/Extensions/PostgresRoutineServiceCollectionExtensions.cs
- src/Core/RevEng.Core.60/Routines/PostgresRoutineModelFactory.cs
- src/Core/RevEng.Core.60/Routines/Procedures/PostgresStoredProcedureModelFactory.cs
- src/Core/RevEng.Core.60/Routines/Procedures/PostgresStoredProcedureScaffolder.cs
Enable type mapper
Initial stab at scaffolding - needs testing
Only support set returning functions for now
relates to #2251
> Postgres initial scaffold

- src/Core/RevEng.Core.80/DacpacReportBuilder.cs
- src/Core/SqlServer.Rules.Report/Report.cs
- src/Core/SqlServer.Rules.Report/ReportFactory.cs
- src/Core/SqlServer.Rules.Report/Resources/RulesTransform.xslt
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.en.vsct
- src/GUI/Shared/Extensions/ProjectExtensions.cs
- src/GUI/Shared/GuidList.cs
- src/GUI/Shared/Handlers/DacpacAnalyzerHandler.cs
- src/GUI/Shared/Handlers/DatabaseDiagramHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/Helpers/SqlProjHelper.cs
- src/GUI/Shared/PkgCmdIDList.cs
- src/GUI/Shared/Shared.projitems
> Dacpac report

- src/Core/RevEng.Core.80/DacpacExtractor.cs
- src/Core/RevEng.Core.80/DacpacReportBuilder.cs
- src/Core/SqlServer.Rules.Report/ReportFactory.cs
- src/Core/efreveng60/Program.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.en.vsct
- src/GUI/Shared/Handlers/DacpacAnalyzerHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/Helpers/VsDataHelper.cs
- src/GUI/Shared/PkgCmdIDList.cs
> Extract and analyze from database

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.en.vsct
- src/GUI/Shared/PkgCmdIDList.cs
> Add Refresh project context menu item

- src/Core/NUnitTestCore/CliObjectListTest.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
> Just warn when removing FK or PK columns

- src/Core/RevEng.Core.60/ColumnRemovingScaffoldingModelFactory.cs
> Remove unique constraint if removed column participates

- samples/CodeTemplates/EFCore/EntityType.t4
- src/Core/RevEng.Core.60/ColumnRemovingScaffoldingModelFactory.cs
> Remove fks with excluded columns

- .gitignore
- src/Core/RevEng.Core.80/DacpacReport/DacpacExtractor.cs
- src/Core/RevEng.Core.80/DacpacReport/DacpacReportBuilder.cs
- src/Core/RevEng.Core.80/DataApiBuilderBuilder/DabBuilder.cs
- src/Core/efreveng60/Program.cs
- src/Core/efreveng60/TestFiles/dabtest.json
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.vsct
- src/GUI/RevEng.Shared/Dab/DataApiBuilderOptions.cs
- src/GUI/RevEng.Shared/Dab/DataApiBuilderOptionsExtensions.cs
- src/GUI/RevEng.Shared/Providers.cs
- src/GUI/Shared/Handlers/DabBuilder/DabBuilderHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ResultDeserializer.cs
- src/GUI/Shared/PkgCmdIDList.cs
- src/GUI/Shared/Shared.projitems
- test/Ef7Playground/Ef7Playground/dab-config.cmd
- test/Ef7Playground/Ef7Playground/dab-options.json
- test/ScaffoldingTester/dab-config.cmd
- test/ScaffoldingTester/dab-config.json
fixes #2393 (stored procs still missing)
> Dab builder POC

- .github/workflows/vsix.yml
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
fixed build for .net 6, 7
updated tools
> Bugfix for dacpac defaultvalue

- .github/workflows/vsix.yml
- src/Core/efreveng60/BuildCmdlineTool.cmd
- src/Core/efreveng70/BuildCmdlineTool.cmd
- src/Core/efreveng80/BuildCmdlineTool.cmd
> Tools build

- .github/workflows/cli-tool.yml
- .github/workflows/vsix.yml
- global.json
- src/Core/RevEng.Core.60/ReverseEngineerRunner.cs
- src/Core/RevEng.Core.60/Routines/Extensions/SqlServerRoutineServiceCollectionExtensions.cs
- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.60/TableListBuilder.cs
- src/Nupkg/ErikEJ.EntityFrameworkCore.7.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.7.SqlServer.Dacpac.csproj
- src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac.csproj
- src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacFunctionModelFactory.cs
- test/ScaffoldingTester/Database/Database.sqlproj
- test/ScaffoldingTester/Database/dbo/Functions/DatabaseScalarFunction1.sql
- test/ScaffoldingTester/Database/dbo/Functions/Function1.sql
> Dacpac functions

- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.80/PatchedSqlServerDatabaseModelFactory.cs
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
> Enhance DataVerse reverse engineering for EF Core 8 and EF Core 9

- src/Core/efcpt.9/efcpt.9.csproj
- src/GUI/RevEng.Shared/Cli/T4Helper.cs
> Fix missing support for T4 template drop in EF Core 9

- src/Core/RevEng.Core.60/ReverseEngineerRunner.cs
> fix validation

- src/Core/RevEng.Core.60/Routines/Procedures/SqlServerStoredProcedureScaffolder.cs
> Allow passing null value for output parameter

- .github/workflows/cli-tool.yml
- .github/workflows/nupkg-release.yml
- .github/workflows/vsix.yml
- global.json
- src/Core/RevEng.Core.60/ReverseEngineerScaffolder.cs
- src/Core/RevEng.Core.60/Routines/Functions/FunctionScaffolder.cs
- src/Core/RevEng.Core.60/Routines/Functions/SqlServerFunctionScaffolder.cs
- src/Core/RevEng.Core.60/Routines/Procedures/PostgresStoredProcedureScaffolder.cs
- src/Core/RevEng.Core.60/Routines/Procedures/ProcedureScaffolder.cs
- src/Core/RevEng.Core.60/Routines/Procedures/SqlServerStoredProcedureScaffolder.cs
- src/Core/RevEng.Core.60/Routines/ScaffoldHelper.cs
- src/Core/RevEng.Core.Abstractions/Metadata/Routine.cs
- src/Core/RevEng.Core.Abstractions/ModuleScaffolderOptions.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/RevEng.Shared/ReverseEngineerOptions.cs
- test/ScaffoldingTester/ScaffoldingTester/Models/NorthwindContext.cs
- test/ScaffoldingTester/ScaffoldingTester/Models/OrderDetail.cs
- test/ScaffoldingTester/ScaffoldingTester/efpt.config.json
> Pascalcase procs and functions

- samples/efcpt-config.schema.json
- src/Core/RevEng.Core.60/ReverseEngineerScaffolder.cs
- src/EFCorePowerTools.sln
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
- src/GUI/RevEng.Shared/Cli/Configuration/CodeGeneration.cs
- src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs
- src/GUI/RevEng.Shared/ReverseEngineerOptions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
> Implement database names for routines option in CLI

- src/Core/RevEng.Core.60/ServiceProviderBuilder.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.vsct
- src/GUI/Shared/Extensions/ProjectExtensions.cs
- src/GUI/Shared/PkgCmdIDList.cs
- src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs
- src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactoryOptions.cs
- test/ScaffoldingTester/ScaffoldingTester5/dab-config.json
> fixes #2640 (missing .dacpac support)

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/Shared/Handlers/DabBuilderHandler.cs
Add ability to launch DAB from the item context menu
fixes #2635
> Add ability to launch DAB from the item context menu

- src/GUI/Shared/ViewModels/PickServerDatabaseViewModel.cs
> Connection candidate

- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
- src/GUI/Shared/Helpers/VSHelper.cs
Show warning sign if there are reveng issues
> Show warning sign if there are reveng issues

- src/Core/RevEng.Core.80/Routines/ScaffoldHelper.cs
> Fix sproc/function naming bug

- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
> inform that EF Core 6 and 7 are unuspported

- .github/workflows/vsix.yml
- src/Core/RevEng.Core.80/ReverseEngineerScaffolder.cs
- src/Core/RevEng.Core.80/Routines/Functions/FunctionScaffolder.cs
- src/Core/RevEng.Core.80/Routines/Procedures/ProcedureScaffolder.cs
> Respect "UseDecimalDataAnnotation" in functions

- src/Core/RevEng.Core.80/Routines/Functions/SqlServerFunctionModelFactory.cs
- src/Core/RevEng.Core.80/Routines/Procedures/SqlServerStoredProcedureModelFactory.cs
- src/Core/RevEng.Core.80/Routines/RoutineScaffolder.cs
- src/Core/RevEng.Core.Abstractions/Metadata/ModuleResultElement.cs
> Add StrigLegth attribute if asked for

- src/Core/RevEng.Core.80/Routines/Functions/SqlServerFunctionModelFactory.cs
- src/Core/RevEng.Core.80/Routines/Procedures/SqlServerStoredProcedureModelFactory.cs
> Get function result scale and precision

- .github/ISSUE_TEMPLATE.md
- src/Core/RevEng.Core.80/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
- src/GUI/RevEng.Shared/Providers.cs
> Enable Oracle for EF Core 9

- .github/workflows/vsix.yml
- src/Core/efreveng90/BuildCmdlineTool.cmd
> Trim build

- src/Core/RevEng.Core.80/ReverseEngineerRunner.cs
This will resolve issue #2724.
> Fixes #2724 - Entity file getting moved incorrectly when Configuration is in the name.

- .github/workflows/vsix.yml
- src/GUI/Shared/Helpers/SqlConnectionStringBuilderHelper.cs
> Support all documented aliases

- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
this is from a bug in an old version of nuget that added it to projects
> remove NuGetPackageImportStamp

- src/Core/RevEng.Core.80/RevEng.Core.80.csproj
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
- src/GUI/RevEng.Shared/Providers.cs
> Update to EF Core 8.0.12 and 9.0.1

- src/GUI/RevEng.Shared/Providers.cs
- tools/code-sign.md
> Add missing support for MySQL with EF Core 9

- src/Core/RevEng.Core.80/ServiceProviderBuilder.cs
- src/Core/RevEng.Core.90/RevEng.Core.90.csproj
- src/Core/SqlServer.Rules.Report/SqlServer.Rules.Report.csproj
- src/GUI/RevEng.Shared/Providers.cs
> Add EF Core 9 Snowflake support

- src/GUI/EFCorePowerTools/Wizard/Wiz2_PickTablesDialog.cs
- src/GUI/EFCorePowerTools/Wizard/Wiz3_EfCoreModelDialog.cs
- src/GUI/EFCorePowerTools/Wizard/Wiz4_StatusDialog.xaml
- src/GUI/EFCorePowerTools/Wizard/Wiz4_StatusDialog.xaml.cs
- src/GUI/EFCorePowerTools/Wizard/WizardResultPageFunction.cs
Navigation and logic updated so that developer can generate files, then navigate to prior page, make updates and generate files again.
> Wizard updated to permit generating / updating multiple times

- src/Core/efcpt.8/HostedServices/ScaffoldHostedService.cs
- src/Core/efcpt.8/Options/ScaffoldOptions.cs
> Add more verbose output (file list for now)

- src/Core/RevEng.Core.80/Diagram/DiagramBuilder.cs
- src/Core/RevEng.Core.80/Diagram/ErDiagramBuilder.cs
- src/Core/efreveng80/Program.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/RevEng.Shared/Dab/DataApiBuilderOptions.cs
- src/GUI/Shared/Handlers/DatabaseDiagramHandler.cs
- src/GUI/Shared/Handlers/ErDiagramHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/EfRevEngLauncher.cs
> Diagram generation did not support "mergedacpacs"

- src/Core/RevEng.Core.80/Diagram/ErDiagramBuilder.cs
- src/GUI/Shared/Handlers/DatabaseDiagramHandler.cs
> Fix more diagram bugs

- samples/efcpt-config.schema.json
- src/Core/NUnitTestCore/CliObjectListTest.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
allow "empty" DbContext from CLI config
> fixes #2849

- src/Core/NUnitTestCore/CustomHumanizerPluralizerTest.cs
- src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs
Test "Delta"
fixes #2855
fixes #2853
> Make column exclusion validation more robust

- src/Core/RevEng.Core.80/ConnectionStringResolver.cs
> Improve CLI provider detection for .dacpac

- src/Core/RevEng.Core.80/ReverseEngineerRunner.cs
> Ensure more valid namespace and identifiers

- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs
- src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.vsct
- src/GUI/Shared/Handlers/DgmlNugetHandler.cs
- src/GUI/Shared/Helpers/ReverseEngineerHelper.cs
- src/GUI/Shared/PkgCmdIDList.cs
> Remove "Add T4 Templates" menu item

- src/Core/RevEng.Core.80/ReverseEngineerRunner.cs
> Support namespace with "."

- src/GUI/PowerToolsExtensionPack/Extensions.vsext
- src/GUI/PowerToolsExtensionPack/source.extension.vsixmanifest
> Add ARM64 support to Power Pack

- src/Core/RevEng.Core.80/ReverseEngineerRunner.cs
> Preserve namespace casing

- .github/workflows/vsix.yml
- fileslist.txt
> Try trusted signing

- .github/workflows/vsix.yml
- src/Core/RevEng.Core.80/Routines/Functions/SqlServerFunctionScaffolder.cs
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
fixes #2921
Updates dependencies in VSIX
> fixes #2921

- src/Core/RevEng.Core.80/Routines/Procedures/PostgresStoredProcedureModelFactory.cs
> Fix missing DateOnly mapping with PostgresSQL

- src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/Scaffolding/SqlServerDacpacStoredProcedureModelFactory.cs
> Fix for bad .dacpac stored procedure result evaluation

- src/GUI/Shared/Extensions/ProjectExtensions.cs
> Allow .NET 10 projects

- src/Core/efcpt.8/HostedServices/RegisterDependentServices.cs
> add missing merge-dacpacs support to CLI

- src/Core/NUnitTestCore/CliConfigMapperTest.cs
- src/GUI/EFCorePowerTools/EFCorePowerTools.csproj
- src/GUI/EFCorePowerTools/Wizard/Wiz2_PickTablesDialog.cs
- src/GUI/RevEng.Shared/ReverseEngineerOptions.cs
- src/GUI/Shared/Handlers/ReverseEngineer/RevEngWizardHandler.cs
- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- src/GUI/Shared/Helpers/SqlProjHelper.cs
- test/ScaffoldingTester/ScaffoldingTester/efpt.config.json
fix missing support for database project in Wizard
> Add minProductVersion to config

- src/Core/RevEng.Core.80/Routines/Extensions/PostgresNpgsqlTypeExtensions.cs
> Support TsQuery Postgres type

- src/GUI/Shared/Helpers/VsDataHelper.cs
> Add ability to set command timeout for SQL Server

- src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerHandler.cs
- test/ScaffoldingTester/DatabaseSdk/DatabaseSdk.sqlproj
> Set correct version in config

- src/Core/RevEng.Core.80/Routines/Procedures/PostgresStoredProcedureScaffolder.cs
- src/Core/RevEng.Core.80/Routines/Procedures/SqlServerStoredProcedureScaffolder.cs
> Fix issue with new overload to ExecuteSqlRawAsync in EF Core 9

- src/Core/efreveng100/BuildCmdlineTool.cmd
- src/Core/efreveng80/BuildCmdlineTool.cmd
- src/Core/efreveng90/BuildCmdlineTool.cmd
> Shrink tools .zip files

- src/GUI/Shared/Handlers/ReverseEngineer/RevEngWizardHandler.cs
Changes from wizard page 1 were not being persisted.  I had to move the code out of wizard page 1 into page 2 so that it pulls the updates made on page 1.  
fixes #3101
> Fix CodeGenerationCode not being persisted 

- src/Core/DacFxStrongTypedCore.161/DacFxStrongTypedCore.161.csproj
- src/Core/SqlServer.Rules.Report/SqlServer.Rules.Report.csproj
- src/GUI/Shared/Helpers/VsDataHelper.cs
- src/Nupkg/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac.csproj
- src/Nupkg/ErikEJ.EntityFrameworkCore.9.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.9.SqlServer.Dacpac.csproj
Improve VsHelper
fixes #3152
fixes #3151
> Update Dacpac Nuget packages

- global.json
> Update tools .zip files
